[package]
name = "tickflow-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
apca = "0.30.0"
dotenvy = "0.15.7"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5"
